import "./note.css";

export default function Note(props) {
  return (
    <div className="field">
      <table>
        <tr>
          <th>{props.ID_head}</th>
          <th>{props.head_head}</th>
          <th>{props.create_head}</th>
          <th>{props.date_head}</th>
          <th>{props.deadline_head}</th>
          <th>{props.description_head}</th>
          <th>{props.edit_head}</th>
          <th>{props.delete_head}</th>
        </tr>
        <tr>
          <td>{props.ID}</td>
          <td>{props.head}</td>
          <td>{props.create}</td>
          <td>{props.date}</td>
          <td>{props.deadline}</td>
          <td>{props.description}</td>
          <td>{props.edit}</td>
          <td>{props.delete}</td>
        </tr>
        <tr>
          <td>{props.ID}</td>
          <td>{props.head}</td>
          <td>{props.create}</td>
          <td>{props.date}</td>
          <td>{props.deadline}</td>
          <td>{props.description}</td>
          <td>{props.edit}</td>
          <td>{props.delete}</td>
        </tr>
        <tr>
          <td>{props.ID}</td>
          <td>{props.head}</td>
          <td>{props.create}</td>
          <td>{props.date}</td>
          <td>{props.deadline}</td>
          <td>{props.description}</td>
          <td>{props.edit}</td>
          <td>{props.delete}</td>
        </tr>
        <tr>
          <td>{props.ID}</td>
          <td>{props.head}</td>
          <td>{props.create}</td>
          <td>{props.date}</td>
          <td>{props.deadline}</td>
          <td>{props.description}</td>
          <td>{props.edit}</td>
          <td>{props.delete}</td>
        </tr>
        <tr>
          <td>{props.ID}</td>
          <td>{props.head}</td>
          <td>{props.create}</td>
          <td>{props.date}</td>
          <td>{props.deadline}</td>
          <td>{props.description}</td>
          <td>{props.edit}</td>
          <td>{props.delete}</td>
        </tr>
        <tr>
          <td>{props.ID}</td>
          <td>{props.head}</td>
          <td>{props.create}</td>
          <td>{props.date}</td>
          <td>{props.deadline}</td>
          <td>{props.description}</td>
          <td>{props.edit}</td>
          <td>{props.delete}</td>
        </tr>
      </table>
    </div>
  );
}
